### ISSUE TITLE
cant post email 

### ISSUE THREAD

**Issue by osmanDaud** [128kcmt/farm-basket#22]
cant post entered email for a password reset to forgotten password API

**Comment by 128kcmt** [comment]
may you provide more details on this issue?

**Comment by 128kcmt** [comment]
I just recently tried to run the endpoint using postman and seems to work just fine. below i have attached a file showing the reset password email i got after testing the endpoint using postman.
![WhatsApp Image 2024-11-20 at 10 48 25 PM](https://github.com/user-attachments/assets/32fb15c3-a061-4afd-9e0b-e6a0265675ba)

**Comment by osmanDaud** [comment]
sorry the error was with my code
